### ISSUE TITLE
Distance between two leaves in Newick parser

### ISSUE THREAD

**Issue by haluk** [sandain/es2#1]
How do you calculate the distance between two leaves? There is a method distanceFromRootNode() but it doesn't help to find the distance between two nodes.

**Comment by sandain** [comment]
Hi haluk.

Just a heads up, ES2 is still under heavy development and has not been fully vetted against environmental data yet.  If you require more stability, the copy of ES1 I have in my repo should be working well.  I'm currently working on a replacement for the Bruteforce method (the ParameterEstimate object was committed yesterday, but it is not hooked up yet).

A NewickTreeNode knows its distance from its parent (getDistance), its distance from the root node as you noticed (distanceFromRootNode), its distance from the most diverged leaf node (maximumDistanceFromLeafNode), and its distance from the least diverged leaf node (minimumDistanceFromLeafNode).  To see how the complete-linkage-like clustering is calculated, take a look at the code in Binning.java, particularly the recursive getNumberBins method.

The NewickTreeNode, NewickTree, and Binning objects are mostly feature complete, but if you see something that could be done in a better way, let me know.

**Comment by sandain** [comment]
I gave your question some more thought.  ES2 does not currently have a use for calculating the distance between two arbitrary nodes (leaf or internal), just between the most divergent leaf nodes for the binning step.  However, if you are just looking to use this code in another project, it wouldn't be hard to add the capability.

My initial thoughts (untested) look something like:
NewickTree.java
```
public Double distanceBetweenLeafNodes (NewickTreeNode a, NewickTreeNode b) {
    Double distance = 0.0d;
    // Check for the same node.
    if (a.compareTo (b) == 0) return distance;
    // Find the last common ancestor of a and b while keeping
    // keeping track of the distance between a and lca.
    distance += a.getDistance ();
    NewickTreeNode lca = a.getParent ();
    while (! lca.getDescendants ().contains (b)) {
        distance += lca.getDistance ();
        lca = lca.getParent ();
    }
    // Add the distance between b and lca.
    distance += b.getDistance ();
    NewickTreeNode node = b.getParent ();
    while (node != lca) {
        distance += node.getDistance ();
        node = node.getParent ();
    }
    return distance;
}

```
